In [1]:
import pandas as pd
import numpy as np
from datetime import datetime
import time

In [1]:
import os
os.chdir("../raw data")

In [3]:
# importing fips data. and rearranging the columns
fips = pd.read_excel("fips.xlsx")
fips = fips.iloc[:, [1, 3, 2, 4, 5]]

# Convert the 'integers' to integers in fips file.
for i in range(fips.shape[0]):
    if fips.iloc[i, 4] != 'unknown':
        fips.iloc[i, 4] = int(fips.iloc[i, 4])
        fips.iloc[i, 2] = int(fips.iloc[i, 2])

In [8]:
newNYT = pd.read_csv("newNYT.csv")
newBU = pd.read_csv("newBU.csv")
mmr = pd.read_csv("mmr.csv")

newNYT = newNYT.iloc[:, 6:]
newBU = newBU.iloc[:, 6:]
mmr = mmr.iloc[:, 6:]

In [13]:
merged = pd.concat([fips, newNYT, newBU, mmr], axis=1)
merged

,stfips,stname,ctyfips,ctyname,fips,2020-01-21_cases,2020-01-22_cases,2020-01-23_cases,2020-01-24_cases,2020-01-25_cases,...,cardiovascular_crudeRate,d_population,diabetes_deaths,diabetes_crudeRate,m_population,mental_deaths,mental_crudeRate,n_population,neoplasm_deaths,neoplasm_crudeRate
0,1,Alabama,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Alabama,1,Autauga County,1001,0,0,0,0,0,...,295.0,55601.0,29.0,52.2,55601.0,13.0,Unreliable,55601.0,95.0,170.9
2,1,Alabama,3,Baldwin County,1003,0,0,0,0,0,...,349.5,218022.0,26.0,11.9,218022.0,113.0,51.8,218022.0,559.0,256.4
3,1,Alabama,5,Barbour County,1005,0,0,0,0,0,...,502.4,NaN,NaN,NaN,24881.0,10.0,Unreliable,24881.0,69.0,277.3
4,1,Alabama,7,Bibb County,1007,0,0,0,0,0,...,464.3,NaN,NaN,NaN,NaN,NaN,NaN,22400.0,59.0,263.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3319,72,Puerto Rico,147,Vieques Municipio,72147,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3320,72,Puerto Rico,149,Villalba Municipio,72149,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3321,72,Puerto Rico,151,Yabucoa Municipio,72151,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3322,72,Puerto Rico,153,Yauco Municipio,72153,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3323,72,Puerto Rico,unknown,unknown,unknown,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
os.chdir("../data")

In [14]:
merged.to_csv("merged.csv")